apiVersion: v1
kind: Service
metadata:
  name: 7dtd-service
spec:
  type: NodePort
  ports:
  - name: server-tcp
    port: 26900
    protocol: TCP
    nodePort: 32100
  - name: server-udp1
    port: 26900
    protocol: UDP
    nodePort: 32100
  - name: server-udp2
    port: 26901
    protocol: UDP
    nodePort: 32101
  - name: server-udp3
    port: 26902
    protocol: UDP
    nodePort: 32102
  - name: webadmin
    port: 8080
    protocol: TCP
    nodePort: 32103
  - name: telnet
    port: 8081
    protocol: TCP
    nodePort: 32104
  - name: alloc-fixes
    port: 8082
    protocol: TCP
    nodePort: 32105

## Uncomment the below section to use a cloud loadbalancer instead of nodeport

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: 7dtd-service
# spec:
#   type: LoadBalancer