apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: 7dtd-server
spec:
  selector:
    matchLabels:
      app: 7dtd-server
  serviceName: 7dtd-service
  replicas: 1
  template:
    metadata:
      labels:
        app: 7dtd-server
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: 7dtd-server
        image: vinanrra/7dtd-server:v0.2.1
        ports:
        - containerPort: 26900
          name: server-tcp
          protocol: TCP
        - containerPort: 26900
          name: server-udp1
          protocol: UDP
        - containerPort: 26901
          name: server-udp2
          protocol: UDP
        - containerPort: 26902
          name: server-udp3
          protocol: UDP
        - containerPort: 8080
          name: webadmin
          protocol: TCP
        - containerPort: 8081
          name: telnet
          protocol: TCP
        - containerPort: 8082
          name: alloc-fixes
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /home/sdtdserver/serverfiles/
          subPath: serverfiles
        - name: data
          mountPath: /home/sdtdserver/.local/share/7DaysToDie/
          subPath: local
        - name: data
          mountPath: /home/sdtdserver/log/
          subPath: log
        - name: data
          mountPath: /home/sdtdserver/lgsm/
          subPath: lgsm
        
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi